import json
import requests
# 新手的第一个程序，爬取豆瓣评分前500的电影名称。
mun = 0

while mun<2000:

    url = "https://movie.douban.com/j/search_subjects?type=movie&tag=%E8%B1%86%E7%93%A3%E9%AB%98%E5%88%86&sort=rank&page_limit=20&page_start={}"

    start_url = url.format(mun)

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",'Referer':'https://movie.douban.com/tag/'}

    response = requests.get(start_url,headers=headers)

    data_str = response.content.decode()

    json_list = json.loads(data_str)

    json_name =json_list['subjects']

    i = 0

    f = open('name3.txt','a',encoding='utf-8')

    while i<=19:

        dict_name = json_name[i]['title']

        f.write(dict_name)
        f.write('\n')
        i += 1

    mun += 20

    print(mun)






